#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: qmake5
# autospec version: v27
# autospec commit: 6aaa12f
#
Name     : qtscript
Version  : 5.15.17
Release  : 35
URL      : https://download.qt.io/official_releases/qt/5.15/5.15.17/submodules/qtscript-everywhere-opensource-src-5.15.17.tar.xz
Source0  : https://download.qt.io/official_releases/qt/5.15/5.15.17/submodules/qtscript-everywhere-opensource-src-5.15.17.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause BSD-3-Clause-Clear GFDL-1.3 GPL-2.0 GPL-3.0 LGPL-2.0 LGPL-3.0
Requires: qtscript-lib = %{version}-%{release}
Requires: qtscript-license = %{version}-%{release}
Requires: qtscript-extras
BuildRequires : mesa-dev
BuildRequires : pkgconfig(Qt5Core)
BuildRequires : pkgconfig(Qt5Gui)
BuildRequires : pkgconfig(Qt5Test)
BuildRequires : pkgconfig(Qt5UiTools)
BuildRequires : pkgconfig(Qt5Widgets)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Qt is provided with a powerful embedded scripting environment through the Qt Script
classes.

%package dev
Summary: dev components for the qtscript package.
Group: Development
Requires: qtscript-lib = %{version}-%{release}
Requires: qtscript-extras = %{version}-%{release}
Provides: qtscript-devel = %{version}-%{release}
Requires: qtscript = %{version}-%{release}

%description dev
dev components for the qtscript package.


%package examples
Summary: examples components for the qtscript package.
Group: Default
Requires: qtscript-dev = %{version}-%{release}

%description examples
examples components for the qtscript package.


%package extras
Summary: extras components for the qtscript package.
Group: Default

%description extras
extras components for the qtscript package.


%package lib
Summary: lib components for the qtscript package.
Group: Libraries
Requires: qtscript-license = %{version}-%{release}

%description lib
lib components for the qtscript package.


%package license
Summary: license components for the qtscript package.
Group: Default

%description license
license components for the qtscript package.


%prep
%setup -q -n qtscript-everywhere-src-5.15.17
cd %{_builddir}/qtscript-everywhere-src-5.15.17

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export QMAKE_CFLAGS="$CFLAGS"
export QMAKE_CXXFLAGS="$CXXFLAGS"
export QMAKE_LFLAGS="$LDFLAGS"
export QMAKE_LIBDIR=/usr/lib64
export QMAKE_CFLAGS_RELEASE=
export QMAKE_CXXFLAGS_RELEASE=
export PATH=/usr/lib64/qt5/bin:$PATH
qmake QMAKE_CFLAGS+=-fno-lto QMAKE_CXXFLAGS+=-fno-lto
test -r config.log && cat config.log
make  %{?_smp_mflags}

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1748667647
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/qtscript
cp %{_builddir}/qtscript-everywhere-src-%{version}/LICENSE.FDL %{buildroot}/usr/share/package-licenses/qtscript/61907422fefcd2313a9b570c31d203a6dbebd333 || :
cp %{_builddir}/qtscript-everywhere-src-%{version}/LICENSE.GPL2 %{buildroot}/usr/share/package-licenses/qtscript/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/qtscript-everywhere-src-%{version}/LICENSE.GPL3 %{buildroot}/usr/share/package-licenses/qtscript/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
cp %{_builddir}/qtscript-everywhere-src-%{version}/LICENSE.GPL3-EXCEPT %{buildroot}/usr/share/package-licenses/qtscript/e93757aefa405f2c9a8a55e780ae9c39542dfc3a || :
cp %{_builddir}/qtscript-everywhere-src-%{version}/LICENSE.LGPL3 %{buildroot}/usr/share/package-licenses/qtscript/f45ee1c765646813b442ca58de72e20a64a7ddba || :
cp %{_builddir}/qtscript-everywhere-src-%{version}/src/3rdparty/javascriptcore/JavaScriptCore/COPYING.LIB %{buildroot}/usr/share/package-licenses/qtscript/130f5281a2ef2a49822787e013323bde2ff119dd || :
cp %{_builddir}/qtscript-everywhere-src-%{version}/src/3rdparty/javascriptcore/JavaScriptCore/pcre/COPYING %{buildroot}/usr/share/package-licenses/qtscript/2b6fa847d802d22e07e3820736fb44c16b993753 || :
cp %{_builddir}/qtscript-everywhere-src-%{version}/tests/benchmarks/script/sunspider/tests/LICENSE.txt %{buildroot}/usr/share/package-licenses/qtscript/b645cd68a59c15141e05c635c05b78d6b9258e6e || :
cp %{_builddir}/qtscript-everywhere-src-%{version}/tests/benchmarks/script/v8/tests/LICENSE.txt %{buildroot}/usr/share/package-licenses/qtscript/d665d19f92487f37fa3b97cc14fad2b3857f1713 || :
export GOAMD64=v2
GOAMD64=v2
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/qt5/QtScript/5.15.17/QtScript/private/qscriptable_p.h
/usr/include/qt5/QtScript/5.15.17/QtScript/private/qscriptactivationobject_p.h
/usr/include/qt5/QtScript/5.15.17/QtScript/private/qscriptast_p.h
/usr/include/qt5/QtScript/5.15.17/QtScript/private/qscriptastfwd_p.h
/usr/include/qt5/QtScript/5.15.17/QtScript/private/qscriptastvisitor_p.h
/usr/include/qt5/QtScript/5.15.17/QtScript/private/qscriptclassobject_p.h
/usr/include/qt5/QtScript/5.15.17/QtScript/private/qscriptcontext_p.h
/usr/include/qt5/QtScript/5.15.17/QtScript/private/qscriptdeclarativeclass_p.h
/usr/include/qt5/QtScript/5.15.17/QtScript/private/qscriptdeclarativeobject_p.h
/usr/include/qt5/QtScript/5.15.17/QtScript/private/qscriptengine_p.h
/usr/include/qt5/QtScript/5.15.17/QtScript/private/qscriptengineagent_p.h
/usr/include/qt5/QtScript/5.15.17/QtScript/private/qscriptfunction_p.h
/usr/include/qt5/QtScript/5.15.17/QtScript/private/qscriptglobalobject_p.h
/usr/include/qt5/QtScript/5.15.17/QtScript/private/qscriptgrammar_p.h
/usr/include/qt5/QtScript/5.15.17/QtScript/private/qscriptlexer_p.h
/usr/include/qt5/QtScript/5.15.17/QtScript/private/qscriptobject_p.h
/usr/include/qt5/QtScript/5.15.17/QtScript/private/qscriptparser_p.h
/usr/include/qt5/QtScript/5.15.17/QtScript/private/qscriptprogram_p.h
/usr/include/qt5/QtScript/5.15.17/QtScript/private/qscriptqobject_p.h
/usr/include/qt5/QtScript/5.15.17/QtScript/private/qscriptstaticscopeobject_p.h
/usr/include/qt5/QtScript/5.15.17/QtScript/private/qscriptstring_p.h
/usr/include/qt5/QtScript/5.15.17/QtScript/private/qscriptsyntaxchecker_p.h
/usr/include/qt5/QtScript/5.15.17/QtScript/private/qscriptvalue_p.h
/usr/include/qt5/QtScript/5.15.17/QtScript/private/qscriptvariant_p.h
/usr/include/qt5/QtScript/5.15.17/QtScript/private/qtscript-config_p.h
/usr/include/qt5/QtScript/QScriptClass
/usr/include/qt5/QtScript/QScriptClassPropertyIterator
/usr/include/qt5/QtScript/QScriptContext
/usr/include/qt5/QtScript/QScriptContextInfo
/usr/include/qt5/QtScript/QScriptContextInfoList
/usr/include/qt5/QtScript/QScriptEngine
/usr/include/qt5/QtScript/QScriptEngineAgent
/usr/include/qt5/QtScript/QScriptExtensionInterface
/usr/include/qt5/QtScript/QScriptExtensionPlugin
/usr/include/qt5/QtScript/QScriptProgram
/usr/include/qt5/QtScript/QScriptString
/usr/include/qt5/QtScript/QScriptSyntaxCheckResult
/usr/include/qt5/QtScript/QScriptValue
/usr/include/qt5/QtScript/QScriptValueIterator
/usr/include/qt5/QtScript/QScriptValueList
/usr/include/qt5/QtScript/QScriptable
/usr/include/qt5/QtScript/QtScript
/usr/include/qt5/QtScript/QtScriptDepends
/usr/include/qt5/QtScript/QtScriptVersion
/usr/include/qt5/QtScript/qscriptable.h
/usr/include/qt5/QtScript/qscriptclass.h
/usr/include/qt5/QtScript/qscriptclasspropertyiterator.h
/usr/include/qt5/QtScript/qscriptcontext.h
/usr/include/qt5/QtScript/qscriptcontextinfo.h
/usr/include/qt5/QtScript/qscriptengine.h
/usr/include/qt5/QtScript/qscriptengineagent.h
/usr/include/qt5/QtScript/qscriptextensioninterface.h
/usr/include/qt5/QtScript/qscriptextensionplugin.h
/usr/include/qt5/QtScript/qscriptprogram.h
/usr/include/qt5/QtScript/qscriptstring.h
/usr/include/qt5/QtScript/qscriptvalue.h
/usr/include/qt5/QtScript/qscriptvalueiterator.h
/usr/include/qt5/QtScript/qtscript-config.h
/usr/include/qt5/QtScript/qtscriptglobal.h
/usr/include/qt5/QtScript/qtscriptversion.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptbreakpointdata_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptbreakpointsmodel_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptbreakpointswidget_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptbreakpointswidgetinterface_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptbreakpointswidgetinterface_p_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptcompletionproviderinterface_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptcompletiontask_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptcompletiontaskinterface_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptcompletiontaskinterface_p_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebugger_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggeragent_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggeragent_p_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggerbackend_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggerbackend_p_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggercodefinderwidget_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggercodefinderwidgetinterface_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggercodefinderwidgetinterface_p_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggercodeview_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggercodeviewinterface_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggercodeviewinterface_p_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggercodewidget_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggercodewidgetinterface_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggercodewidgetinterface_p_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggercommand_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggercommandexecutor_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggercommandschedulerfrontend_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggercommandschedulerinterface_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggercommandschedulerjob_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggercommandschedulerjob_p_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggerconsole_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggerconsolecommand_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggerconsolecommand_p_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggerconsolecommandgroupdata_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggerconsolecommandjob_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggerconsolecommandjob_p_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggerconsolecommandmanager_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggerconsoleglobalobject_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggerconsolehistorianinterface_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggerconsolewidget_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggerconsolewidgetinterface_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggerconsolewidgetinterface_p_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggerevent_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggereventhandlerinterface_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggerfrontend_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggerfrontend_p_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggerjob_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggerjob_p_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggerjobschedulerinterface_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggerlocalsmodel_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggerlocalswidget_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggerlocalswidgetinterface_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggerlocalswidgetinterface_p_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggerobjectsnapshotdelta_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggerresponse_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggerresponsehandlerinterface_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggerscriptedconsolecommand_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggerscriptsmodel_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggerscriptswidget_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggerscriptswidgetinterface_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggerscriptswidgetinterface_p_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggerstackmodel_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggerstackwidget_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggerstackwidgetinterface_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggerstackwidgetinterface_p_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggerstandardwidgetfactory_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggervalue_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggervalueproperty_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebuggerwidgetfactoryinterface_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebugoutputwidget_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebugoutputwidgetinterface_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptdebugoutputwidgetinterface_p_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptedit_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptenginedebuggerfrontend_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscripterrorlogwidget_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscripterrorlogwidgetinterface_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscripterrorlogwidgetinterface_p_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptmessagehandlerinterface_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptobjectsnapshot_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptscriptdata_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptstdmessagehandler_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptsyntaxhighlighter_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscripttooltipproviderinterface_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptvalueproperty_p.h
/usr/include/qt5/QtScriptTools/5.15.17/QtScriptTools/private/qscriptxmlparser_p.h
/usr/include/qt5/QtScriptTools/QScriptEngineDebugger
/usr/include/qt5/QtScriptTools/QtScriptTools
/usr/include/qt5/QtScriptTools/QtScriptToolsDepends
/usr/include/qt5/QtScriptTools/QtScriptToolsVersion
/usr/include/qt5/QtScriptTools/qscriptenginedebugger.h
/usr/include/qt5/QtScriptTools/qtscripttoolsversion.h
/usr/lib64/cmake/Qt5Script/Qt5ScriptConfig.cmake
/usr/lib64/cmake/Qt5Script/Qt5ScriptConfigVersion.cmake
/usr/lib64/cmake/Qt5ScriptTools/Qt5ScriptToolsConfig.cmake
/usr/lib64/cmake/Qt5ScriptTools/Qt5ScriptToolsConfigVersion.cmake
/usr/lib64/libQt5Script.prl
/usr/lib64/libQt5Script.so
/usr/lib64/libQt5ScriptTools.prl
/usr/lib64/libQt5ScriptTools.so
/usr/lib64/pkgconfig/Qt5Script.pc
/usr/lib64/pkgconfig/Qt5ScriptTools.pc
/usr/lib64/qt5/mkspecs/modules/qt_lib_script.pri
/usr/lib64/qt5/mkspecs/modules/qt_lib_script_private.pri
/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools.pri
/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools_private.pri

%files examples
%defattr(-,root,root,-)
/usr/share/qt5/examples/script/README
/usr/share/qt5/examples/script/calculator/calculator.js
/usr/share/qt5/examples/script/calculator/calculator.pro
/usr/share/qt5/examples/script/calculator/calculator.qrc
/usr/share/qt5/examples/script/calculator/calculator.ui
/usr/share/qt5/examples/script/calculator/main.cpp
/usr/share/qt5/examples/script/context2d/context2d.cpp
/usr/share/qt5/examples/script/context2d/context2d.h
/usr/share/qt5/examples/script/context2d/context2d.pro
/usr/share/qt5/examples/script/context2d/context2d.qrc
/usr/share/qt5/examples/script/context2d/domimage.cpp
/usr/share/qt5/examples/script/context2d/domimage.h
/usr/share/qt5/examples/script/context2d/environment.cpp
/usr/share/qt5/examples/script/context2d/environment.h
/usr/share/qt5/examples/script/context2d/main.cpp
/usr/share/qt5/examples/script/context2d/qcontext2dcanvas.cpp
/usr/share/qt5/examples/script/context2d/qcontext2dcanvas.h
/usr/share/qt5/examples/script/context2d/scripts/alpha.js
/usr/share/qt5/examples/script/context2d/scripts/arc.js
/usr/share/qt5/examples/script/context2d/scripts/bezier.js
/usr/share/qt5/examples/script/context2d/scripts/clock.js
/usr/share/qt5/examples/script/context2d/scripts/fill1.js
/usr/share/qt5/examples/script/context2d/scripts/grad.js
/usr/share/qt5/examples/script/context2d/scripts/linecap.js
/usr/share/qt5/examples/script/context2d/scripts/linestye.js
/usr/share/qt5/examples/script/context2d/scripts/moveto.js
/usr/share/qt5/examples/script/context2d/scripts/moveto2.js
/usr/share/qt5/examples/script/context2d/scripts/pacman.js
/usr/share/qt5/examples/script/context2d/scripts/plasma.js
/usr/share/qt5/examples/script/context2d/scripts/pong.js
/usr/share/qt5/examples/script/context2d/scripts/quad.js
/usr/share/qt5/examples/script/context2d/scripts/rgba.js
/usr/share/qt5/examples/script/context2d/scripts/rotate.js
/usr/share/qt5/examples/script/context2d/scripts/scale.js
/usr/share/qt5/examples/script/context2d/scripts/stroke1.js
/usr/share/qt5/examples/script/context2d/scripts/translate.js
/usr/share/qt5/examples/script/context2d/window.cpp
/usr/share/qt5/examples/script/context2d/window.h
/usr/share/qt5/examples/script/customclass/bytearrayclass.cpp
/usr/share/qt5/examples/script/customclass/bytearrayclass.h
/usr/share/qt5/examples/script/customclass/bytearrayclass.pri
/usr/share/qt5/examples/script/customclass/bytearrayprototype.cpp
/usr/share/qt5/examples/script/customclass/bytearrayprototype.h
/usr/share/qt5/examples/script/customclass/customclass.pro
/usr/share/qt5/examples/script/customclass/main.cpp
/usr/share/qt5/examples/script/defaultprototypes/code.js
/usr/share/qt5/examples/script/defaultprototypes/defaultprototypes.pro
/usr/share/qt5/examples/script/defaultprototypes/defaultprototypes.qrc
/usr/share/qt5/examples/script/defaultprototypes/main.cpp
/usr/share/qt5/examples/script/defaultprototypes/prototypes.cpp
/usr/share/qt5/examples/script/defaultprototypes/prototypes.h
/usr/share/qt5/examples/script/helloscript/helloscript.js
/usr/share/qt5/examples/script/helloscript/helloscript.pro
/usr/share/qt5/examples/script/helloscript/helloscript.qrc
/usr/share/qt5/examples/script/helloscript/main.cpp
/usr/share/qt5/examples/script/marshal/main.cpp
/usr/share/qt5/examples/script/marshal/marshal.pro
/usr/share/qt5/examples/script/qscript/main.cpp
/usr/share/qt5/examples/script/qscript/qscript.pro
/usr/share/qt5/examples/script/qsdbg/example.js
/usr/share/qt5/examples/script/qsdbg/main.cpp
/usr/share/qt5/examples/script/qsdbg/qsdbg.pri
/usr/share/qt5/examples/script/qsdbg/qsdbg.pro
/usr/share/qt5/examples/script/qsdbg/scriptbreakpointmanager.cpp
/usr/share/qt5/examples/script/qsdbg/scriptbreakpointmanager.h
/usr/share/qt5/examples/script/qsdbg/scriptdebugger.cpp
/usr/share/qt5/examples/script/qsdbg/scriptdebugger.h
/usr/share/qt5/examples/script/qstetrix/main.cpp
/usr/share/qt5/examples/script/qstetrix/qstetrix.pro
/usr/share/qt5/examples/script/qstetrix/tetrix.qrc
/usr/share/qt5/examples/script/qstetrix/tetrixboard.cpp
/usr/share/qt5/examples/script/qstetrix/tetrixboard.h
/usr/share/qt5/examples/script/qstetrix/tetrixboard.js
/usr/share/qt5/examples/script/qstetrix/tetrixpiece.js
/usr/share/qt5/examples/script/qstetrix/tetrixwindow.js
/usr/share/qt5/examples/script/qstetrix/tetrixwindow.ui
/usr/share/qt5/examples/script/script.pro

%files extras
%defattr(-,root,root,-)
/usr/lib64/libQt5ScriptTools.so.5
/usr/lib64/libQt5ScriptTools.so.5.15

%files lib
%defattr(-,root,root,-)
/usr/lib64/libQt5Script.so.5
/usr/lib64/libQt5Script.so.5.15
/usr/lib64/libQt5Script.so.5.15.17
/usr/lib64/libQt5ScriptTools.so.5.15.17

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/qtscript/130f5281a2ef2a49822787e013323bde2ff119dd
/usr/share/package-licenses/qtscript/2b6fa847d802d22e07e3820736fb44c16b993753
/usr/share/package-licenses/qtscript/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/qtscript/61907422fefcd2313a9b570c31d203a6dbebd333
/usr/share/package-licenses/qtscript/8624bcdae55baeef00cd11d5dfcfa60f68710a02
/usr/share/package-licenses/qtscript/b645cd68a59c15141e05c635c05b78d6b9258e6e
/usr/share/package-licenses/qtscript/d665d19f92487f37fa3b97cc14fad2b3857f1713
/usr/share/package-licenses/qtscript/e93757aefa405f2c9a8a55e780ae9c39542dfc3a
/usr/share/package-licenses/qtscript/f45ee1c765646813b442ca58de72e20a64a7ddba
